# Generated by Django 2.2.5 on 2020-06-08 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20200608_2253'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HouseRoule',
            new_name='HouseRule',
        ),
    ]
